- name: Run tests with coverage
  run: |
    poetry run pytest --cov=gendiff --cov-report=xml:coverage.xml

- name: SonarCloud Scan
  uses: SonarSource/sonarcloud-github-action@v2
  env:
    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  with:
    args: >
      -Dsonar.projectKey=n3wbiexgod_python-project-50
      -Dsonar.organization=n3wbiexgod
      -Dsonar.python.coverage.reportPaths=coverage.xml